"""Create animals table

Revision ID: 33c0ccd7c108
Revises: 
Create Date: 2026-01-14 13:17:30.233873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33c0ccd7c108'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('shelter_date', sa.Date(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('image_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_animals_search', 'animals', ['species', 'sex', 'location'], unique=False)
    op.create_index(op.f('ix_animals_location'), 'animals', ['location'], unique=False)
    op.create_index(op.f('ix_animals_sex'), 'animals', ['sex'], unique=False)
    op.create_index(op.f('ix_animals_shelter_date'), 'animals', ['shelter_date'], unique=False)
    op.create_index(op.f('ix_animals_species'), 'animals', ['species'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_species'), table_name='animals')
    op.drop_index(op.f('ix_animals_shelter_date'), table_name='animals')
    op.drop_index(op.f('ix_animals_sex'), table_name='animals')
    op.drop_index(op.f('ix_animals_location'), table_name='animals')
    op.drop_index('idx_animals_search', table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
